"""Fild here_date change to Date

Revision ID: 173d771e84fc
Revises: c2925d411db3
Create Date: 2023-07-06 12:50:51.654044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '173d771e84fc'
down_revision = 'c2925d411db3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
