"""Changes in EmployeeHistory table

Revision ID: 3924ba18dee8
Revises: 173d771e84fc
Create Date: 2023-07-06 14:35:49.111104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3924ba18dee8'
down_revision = '173d771e84fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees_history', sa.Column('new_last_name', sa.String(), nullable=True))
    op.add_column('employees_history', sa.Column('old_last_name', sa.String(), nullable=True))
    op.add_column('employees_history', sa.Column('new_position', sa.String(), nullable=True))
    op.add_column('employees_history', sa.Column('old_position', sa.String(), nullable=True))
    op.add_column('employees_history', sa.Column('new_department', sa.String(), nullable=True))
    op.add_column('employees_history', sa.Column('old_department', sa.String(), nullable=True))
    op.add_column('employees_history', sa.Column('new_address', sa.String(), nullable=True))
    op.add_column('employees_history', sa.Column('old_address', sa.String(), nullable=True))
    op.add_column('employees_history', sa.Column('new_status', sa.String(), nullable=True))
    op.add_column('employees_history', sa.Column('old_status', sa.String(), nullable=True))
    op.drop_column('employees_history', 'position')
    op.drop_column('employees_history', 'change_type')
    op.drop_column('employees_history', 'change_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees_history', sa.Column('change_time', sa.DATETIME(), nullable=True))
    op.add_column('employees_history', sa.Column('change_type', sa.VARCHAR(), nullable=True))
    op.add_column('employees_history', sa.Column('position', sa.VARCHAR(), nullable=True))
    op.drop_column('employees_history', 'old_status')
    op.drop_column('employees_history', 'new_status')
    op.drop_column('employees_history', 'old_address')
    op.drop_column('employees_history', 'new_address')
    op.drop_column('employees_history', 'old_department')
    op.drop_column('employees_history', 'new_department')
    op.drop_column('employees_history', 'old_position')
    op.drop_column('employees_history', 'new_position')
    op.drop_column('employees_history', 'old_last_name')
    op.drop_column('employees_history', 'new_last_name')
    # ### end Alembic commands ###
