"""Changing in datatime

Revision ID: 552c7c1b7b7d
Revises: 9a140f6cb62f
Create Date: 2023-07-27 10:06:54.181492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552c7c1b7b7d'
down_revision = '9a140f6cb62f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
