"""Corrected table EmployeeHistory rename heads

Revision ID: 9a140f6cb62f
Revises: 7557fd8c1f95
Create Date: 2023-07-26 17:07:57.565176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a140f6cb62f'
down_revision = '7557fd8c1f95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees_history', sa.Column('old_last_name', sa.String(), nullable=True))
    op.add_column('employees_history', sa.Column('old_position', sa.String(), nullable=True))
    op.add_column('employees_history', sa.Column('old_department', sa.String(), nullable=True))
    op.add_column('employees_history', sa.Column('old_address', sa.String(), nullable=True))
    op.add_column('employees_history', sa.Column('old_status', sa.String(), nullable=True))
    op.drop_column('employees_history', 'new_address')
    op.drop_column('employees_history', 'new_position')
    op.drop_column('employees_history', 'new_status')
    op.drop_column('employees_history', 'new_last_name')
    op.drop_column('employees_history', 'new_department')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees_history', sa.Column('new_department', sa.VARCHAR(), nullable=True))
    op.add_column('employees_history', sa.Column('new_last_name', sa.VARCHAR(), nullable=True))
    op.add_column('employees_history', sa.Column('new_status', sa.VARCHAR(), nullable=True))
    op.add_column('employees_history', sa.Column('new_position', sa.VARCHAR(), nullable=True))
    op.add_column('employees_history', sa.Column('new_address', sa.VARCHAR(), nullable=True))
    op.drop_column('employees_history', 'old_status')
    op.drop_column('employees_history', 'old_address')
    op.drop_column('employees_history', 'old_department')
    op.drop_column('employees_history', 'old_position')
    op.drop_column('employees_history', 'old_last_name')
    # ### end Alembic commands ###
