"""Fild birth_date change to Date

Revision ID: c2925d411db3
Revises: 039464fc0371
Create Date: 2023-07-05 16:29:59.743619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2925d411db3'
down_revision = '039464fc0371'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
